課題16 system spec作成
knykd/sample_app_for_rspec pull request #3
Opened 2019-11-08 10:24 UTC by knykd

* タスクとユーザーに関するsystem specを作成
* bundle exec rspec --format documentation 実行結果
[![Image from Gyazo](https://i.gyazo.com/f9fb1f7848f19ca482e3c4d40cedbbcd.png)](https://gyazo.com/f9fb1f7848f19ca482e3c4d40cedbbcd)

2019-11-08 10:35 UTC, yuji91 commented on Gemfile
> +  gem 'selenium-webdriver'
`gem 'selenium-webdriver'` は `gem 'webdrivers'`があれば不要です。

2019-11-08 10:36 UTC, yuji91 commented on spec/support/capybara.rb
> +require 'selenium-webdriver'
`require 'webdrivers'` にするべきか、そもそも不要かを検証してください！

2019-11-08 11:03 UTC, yuji91 commented on spec/system/tasks_spec.rb
> +          expect(current_path).to eq edit_task_path(user.tasks.ids)
`user.tasks.ids`だと taskが複数件DBにある場合、配列が返ることで pathがうまく作成できなくなると思います。 `task_by_logined_user`をそのまま入れてIDからURLを生成する形で良いと思います！

2019-11-08 11:08 UTC, yuji91 commented on spec/system/tasks_spec.rb
> +        }.to change{ Task.count }.by(-1)
場合によっては Task.count のようにModelからDBアクセスを行うとRspec実行時の実行速度、負荷が高くなってしまうので、避けるというケースもあります。
多用するケースでは問題視されますが、今回はこのままで大丈夫です。

2019-11-08 11:08 UTC, yuji91 commented on spec/system/user_sessions_spec.rb
> +        login_as(user)
expectがないで失敗時に検知できないと思います！

2019-11-08 11:11 UTC, yuji91 commented on spec/system/users_spec.rb
> +        let!(:user) { create(:user) }
letが散らばってしまうと、対象のSpecファイルでどんなテストデータを使っているかどうかの見通しが良くないので、出来るだけ一番上の階層に定義をまとめた方が良いですね。
今回のケースであれば let! で即時実行させずに let で都度必要なケースで実行した方が良いかもしれません。

2019-11-08 11:15 UTC, yuji91 commented on spec/system/tasks_spec.rb
> +      it '編集・削除が表示されない' do
`'編集・削除のリンクが表示されない'` と明示した方が良いですね。

2019-11-08 11:38 UTC, yuji91 commented on spec/system/users_spec.rb
> +  include LoginSupport
`include LoginSupport` は各Specファイルではなく rails_helperなどの設定ファイルから読み込むようにしてください！

2019-11-08 11:39 UTC, yuji91 requested changes
コメントしました！

2019-11-08 11:57 UTC, yuji91 commented on spec/system/users_spec.rb
> +          expect(current_path).to eq task_path(user.tasks.ids)
ここのcurrent_pathの確認は現状のまま変更しなくて良いです！
（DBからtaskのidを取得して確認せざるを得ないため）

2019-11-11 02:23 UTC, knykd commented on spec/system/user_sessions_spec.rb
> +        login_as(user)
こちらspec/support/login_support.rbにログイン時の処理をまとめており、こちらでexpectを記載しています。これだとよくないでしょうか？

2019-11-11 08:51 UTC, yuji91 commented on spec/system/user_sessions_spec.rb
> +        login_as(user)
一般的には supportのmoduleに記載したメソッドで`expect`を書くことはないですね。
expectは各Rspecのdescribe, itで記載し、supportでは共通化するための処理のみを記載することで、各ファイルの役割が明確になります。

上記のitでは supportを確認しないとこのテストケースで何を確認しているのかが分からないので、expectの内容はこちらに記載した方が良いです！

2019-11-11 08:52 UTC, yuji91 commented on spec/system/user_sessions_spec.rb
> +        user
login_as(user)で遅延評価するので上記userは不要になると思います。

2019-11-11 08:55 UTC, yuji91 commented
コメントしました。
https://github.com/knykd/sample_app_for_rspec/pull/3#discussion_r344608064

2019-11-11 08:59 UTC, yuji91 commented on Gemfile
> +  gem 'selenium-webdriver'
b8b114d で修正しました

2019-11-11 09:00 UTC, yuji91 commented on spec/support/capybara.rb
> +require 'selenium-webdriver'
b8b114d で対応。不要なので削除しました。

2019-11-11 09:05 UTC, yuji91 commented on spec/system/tasks_spec.rb
> +          expect(current_path).to eq edit_task_path(user.tasks.ids)
b8b114d で修正しました

2019-11-11 09:06 UTC, yuji91 commented on spec/system/users_spec.rb
> +        let!(:user) { create(:user) }
b8b114d で対応。let! で即時実行させずに一番上の階層に定義をまとめました。

2019-11-11 09:06 UTC, yuji91 commented on spec/system/tasks_spec.rb
> +      it '編集・削除が表示されない' do
b8b114d で修正しました

2019-11-11 09:08 UTC, yuji91 commented on spec/system/users_spec.rb
> +  include LoginSupport
b8b114d で対応。`rails_helper.rb`で読み込むようにしました。

2019-11-11 09:12 UTC, yuji91 requested changes
2点コメントしました。
また、コミットの際は指摘事項1つに対し1コミットに単位を分けた方が確認しやすいです。
(1コミットにまとまってしまうと、全ての変更差分から修正箇所を目視で確認しなければならないので。。)

https://github.com/knykd/sample_app_for_rspec/pull/3#discussion_r344611120 や https://github.com/knykd/sample_app_for_rspec/pull/3#discussion_r344613410 のように自分が例としてコメントしましたが、指摘事項に対して該当のコミットIDを返答することで、レビュー時の確認がスムーズになります。ぜひ試してみてください。

2019-11-11 11:06 UTC, knykd commented on spec/system/user_sessions_spec.rb
> +        login_as(user)
承知しました。602ee51で修正しました！

2019-11-11 11:06 UTC, knykd commented on spec/system/user_sessions_spec.rb
> +        user
こちら4cf725fで修正しました！

2019-11-11 11:44 UTC, shurijoc approved these changes
確認しました。LGTMです！

2019-11-11 12:09 UTC, merged